
package com.sltc.soa.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyConverterWebServer", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyConverterWebServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "currencyConverterSourceUsd", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterSourceUsd")
    @ResponseWrapper(localName = "currencyConverterSourceUsdResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterSourceUsdResponse")
    @Action(input = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterSourceUsdRequest", output = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterSourceUsdResponse")
    public String currencyConverterSourceUsd(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "currencyConverterWithOutUsd", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterWithOutUsd")
    @ResponseWrapper(localName = "currencyConverterWithOutUsdResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterWithOutUsdResponse")
    @Action(input = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterWithOutUsdRequest", output = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterWithOutUsdResponse")
    public String currencyConverterWithOutUsd(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "currencyConverterTargetUsd", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterTargetUsd")
    @ResponseWrapper(localName = "currencyConverterTargetUsdResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterTargetUsdResponse")
    @Action(input = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterTargetUsdRequest", output = "http://soa.sltc.com/CurrencyConverterWebServer/currencyConverterTargetUsdResponse")
    public String currencyConverterTargetUsd(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
